import streamlit as st

st.sidebar.success("Select above page.")

st.title(":green[FAQs about Customer Churn]")
st.subheader(":blue[1. What is Customer Churn ?]")
st.write("Customer churn is the percentage of customers that stopped using your company's product or service during a certain time frame. You can calculate churn rate by dividing the number of customers you lost during that time period -- say a quarter -- by the number of customers you had at the beginning of that time period.")
st.write("For example, if you start your quarter with 400 customers and end with 380, your churn rate is 5% because you lost 5% of your customers.")
st.write("Obviously, your company should aim for a churn rate that is as close to 0% as possible. In order to do this, your company has to be on top of its churn rate at all times and treat it as a top priority.")
st.write("In this example, I calculated the churn rate as the percentage of customers lost that quarter. However, you can calculate churn rate in whatever way is best for your company. Some examples are:")
st.write("1. The number of customers lost")
st.write("2. The value of recurring business lost")
st.write("3. The percentage of recurring value lost")
st.subheader(":blue[2. Why Is Customer Churn Rate Is Important ?]")
st.write("You may be wondering why it's necessary to calculate churn rate. Naturally, you're going to lose some customers here and there, and 5% doesn't sound too bad, right?")
st.write("Well, it's important because it costs more to acquire new customers than it does to retain existing customers. In fact, an increase in customer retention of just 5% can create at least a 25% increase in profit. This is because returning customers will likely spend 67% more on your company's products and services. As a result, your company can spend less on the operating costs of having to acquire new customers. You don't need to spend time and money on convincing an existing customer to select your company over competitors because they've already made that decision.")
st.write("Again, it might seem like a 5% churn rate is solid and healthy. You can still make a vast revenue with that churn rate. However, consider the example below when thinking about the impact of your churn rate.")
st.write("In this example, simply decreasing your churn rate by 10% could add an extra $100,000 in revenue to your company. Dropping from 3% to 2.7% doesn't seem like a lot, but it actually adds large benefits to your company.")
st.subheader(":blue[3. How to Reduce Customer Churn ?]")
st.subheader("1. Focus your attention on your best customers.")
st.write("Rather than simply focusing on offering incentives to customers who are considering churning, it could be even more beneficial to pool your resources into your loyal, profitable customers.")
st.subheader("2. Analyze churn as it occurs.")
st.write("Use your churned customers as a means of understanding why customers are leaving. Analyze how and when churn occurs in a customer's lifetime with your company, and use that data to put into place preemptive measures.")
st.subheader("3. Show your customers that you care.")
st.write("Rather than simply focusing on offering incentives to customers who are considering churning, it could be even more beneficial to pool your resources into your loyal, profitable customers.")
st.subheader(":blue[4. What is Customer Churn Rate ?]")
st.write("Customer churn rate is the percentage of your customers or subscribers who cancel or don't renew their subscriptions during a given time period, such as a month or a year.")
st.write("Churn rate is a critically important metric for companies whose customers pay on a recurring basis — like SaaS or other subscription-based companies. Regardless of your monthly revenue, if your typical customer doesn't stick around long enough for you to recoup your average customer acquisition cost (CAC), you're in trouble.")
st.write("Using a CRM can help you determine your customer churn rate. The software you sell may also have a built-in subscriber count that shows you how many users you had at the beginning of a time period and how many users you had at the end.")
st.subheader(":blue[5. Churn Rate Formula.]")
st.write("The churn rate formula is: (Lost Customers ÷ Total Customers at the Start of Time Period) x 100. For example, if your business had 250 customers at the beginning of the month and lost 10 customers by the end, you would divide 10 by 250. The answer is 0.04. You then multiply 0.04 by 100, resulting in a 4% monthly churn rate.")
st.subheader(":blue[6. How to Calculate Churn Rate ?]")
st.write("To calculate churn rate, you need to have the number of customers you had at the beginning of a given time period, such as monthly or annually, and the number of customers you lost during that time period. Divide the number of lost customers by the total number of customers you had at the start of the time period. Then, multiply this number by 100 to get your churn rate as a percentage.")
st.write("Remember, the steps to calculate churn rate are:")
st.write("1. Determine a time period: monthly, annual, or quarterly.")
st.write("2. Determine the number of customers you had at the beginning of the time period.")
st.write("3. Determine the number of customers that churned by the end of the time period.")
st.write("4. Divide the number of lost customers by the number of customers you had prior to the churn.")
st.write("5. Multiply that number by 100.")
st.write("As an example, let's say your software company had 500 customers at the beginning of last quarter.")
st.write("However, you also lost 50 customers due to expired contracts and a few poor customer service interactions.")
st.write("This would mean your quarter's customer churn rate would be the 50 churned customers divided by the 500 former customers, and 50 divided by 500 is 0.10.")
st.write("Multiplied by 100, this gives you a customer churn rate of 10%.")
st.write("Here's how it looks when you do the math out:")
st.write("Customer Churn Rate = (Lost Customers ÷ Total Customers at the Start of Time Period) x 100")
st.write("Customer Churn Rate = (50 ÷ 500) x 100")
st.write("Customer Churn Rate = (0.10) x 100")
st.write("Customer Churn Rate = 10%")
st.write("Now that you've found out what your churn rate is, you're probably wondering what you should do next — especially if your churn rate is high. Take a look at the next section for some best practices that can help you decrease churn at your business.")
st.subheader(":blue[7. Steps to Take After Calculating Churn Rate.]")
st.write("Is your churn rate high? There are several strategies you could implement to decrease it. If you don't actively work to lower the churn rate, your company could suffer in the long-term.")
st.subheader("1. Analyze churn to improve your customer service team.")
st.write("Despite your best efforts, customer churn will happen and when it does, use it as an opportunity to dig into what led the customer to leave, and what you can do to prevent a similar customer from churning for the same reason.")
st.write("One crucial step is to track your churn and retention rates. You can do this with HubSpot's Customer Service Metrics Calculator — a free tool to calculate and document your retention rate over time.")
st.write("You can use instances of churn to dig into individual customer support rep or manager performance, analyze your product or service against competitors, or identify challenges in the customer experience that you want to remedy with the help of your product and development teams.")
st.subheader("2. Revamp your onboarding plan for new customers.")
st.write("You can work to prevent customer churn from the moment someone becomes a customer by creating a robust new onboarding process. Use a new customer welcome email and offer dedicated 1:1 and online customer onboarding. You can also create educational content on your blog, social media, and video channels to instruct customers and show them how to get optimal value from your product or service.")
st.subheader("3. Invest in more training for support and sales reps.")
st.write("Sales reps should be selling the true value of your product or service so customers don't feel swindled. Additionally, customer support employees should be well-equipped to manage any issue that comes their way to secure customer satisfaction. Investing in processes and resources for these two departments can have a drastic impact on churn rate.")
st.subheader("4. Ask for feedback at key moments — and respond promptly.")
st.write("Make sure you're constantly asking for customer feedback at key moments across the customer experience. If you've already identified that customers are likely to churn if they don't log into your tool every 15 days, ask them for feedback around day 10 and try to re-engage them.")
st.write("If they hit a milestone using your product or service, ask them for feedback after that moment. Figure out the key moments that make or break a happy customer and ask for feedback at those touchpoints to strengthen the relationship.")
st.write("Sometimes, customer feedback comes in the form of negative customer reviews — in which case you'll want to respond promptly and appropriately.")
st.subheader("5. Communicate proactively with customers.")
st.write("Build rapport with your customers by communicating with them proactively so they view you as a trusted partner. Periodically reach out with content you think they'll find interesting or helpful, connect and engage with them on social media, and reach out if issues or outages crop up on the product side so they know they can depend on you.")
st.subheader("6. Offer exclusive perks to existing customers.")
st.write("To prevent further churn, you can offer perks to your current customers. While you could potentially institute a reward program, that's a better fit for retail businesses. You can instead opt for personalized touch-points every once in a while, such as an in-person coffee chat or personal visit to their office.")
st.write("If your business is small, you can also have the CEO personally check in with existing customers to find out how they're doing. This is also a great opportunity to get feedback. A busy customer may not take a survey, but if the CEO asks them if they have any comments, the customer may be more likely to respond.")
st.subheader("7. Leverage feedback from free trial customers.")
st.write("Churn doesn't happen until you lose revenue after a customer leaves your business. But if someone doesn't purchase your product after a free trial, that can be counted as churn — metaphorically speaking.")
st.write("Carry out a survey of those who didn't purchase your product after a free trial. A customer who's already left the business likely won't answer many questions about your product or why it didn't work for them. Someone who took a free trial and ultimately didn't end up making a purchase will expect a survey link. They've also had little interaction with your business, so they're more likely to be frank.")
st.write("Use this feedback to improve your product and learn what makes customers 'churn' before they even become a paying subscriber.")
st.write("Pair these tips with customer retention strategies to lower churn rate.")
st.subheader(":blue[8. Churn Rate Examples.]")
st.write("Many SaaS companies, specifically in the B2C space, publish their churn rates to show how well they retain customers. Use these examples to guide your understanding of your own churn rate — what it should look like for your business and where some famous companies lie on the spectrum.")
st.subheader("Netflix: 3.3% Monthly Churn Rate")
st.write("Netflix has one of the lowest churn rates in the video streaming industry. Its monthly churn rate is strikingly low at 3.5%, meaning that just over 96% of customers choose to stay with Netflix. Causes may include its expansive catalog of shows and its well-established brand voice.")
st.subheader("Disney+: 3.7% Monthly Churn Rate")
st.write("Disney has always avoided being part of other streaming services, and it launched its own service to distribute its shows online. Disney+'s monthly churn rate is 5%, as of March 2023. Churn rates for the Disney Bundle, which includes Disney+, Hulu, and ESPN+, is even lower at just 2%.")
st.subheader("Spotify: 3.9% Monthly Churn Rate")
st.write("Spotify is a popular music streaming service that's known for its personalized recommendations and expansive music library. It has a reported churn rate of 3.9% at the end of 2021 according to CFO Paul Vogel.")
st.subheader("Hulu: 5.2% Monthly Churn Rate")
st.write("Hulu is one of Netflix's principal competitors. Well-known for its exclusive TV shows, it has an 11% market share in the video streaming industry and a 4.7% churn rate.")
st.subheader("Peloton: 1.41% Monthly Churn Rate")
st.write("Peloton has a 1.1% monthly churn rate. The exercise equipment and fitness subscription company may enjoy a high retention rate for being the first in-home cycling fitness subscription. Its status as the first of its kind has cemented its subscriber base.")
st.subheader("Adobe: 10% Yearly Churn Rate")
st.write("According to Rob Giglio, former Vice President of Adobe's Digital Media, Adobe has less than a 10% yearly churn rate and over a 90% customer retention rate.")
st.subheader("Apple TV+: 15.6% Monthly Churn Rate")
st.write("Apple TV+'s monthly churn rate is at 15.6%. Some outlets have reported that it's as high as 20%. A tech journalist called it the 'most unloved' of Apple's platforms. Another has argued that its catalog is 'tiny' and that the content is largely non-original. Additionally, many Apple users were on a free trial and Apple had been extending promotional periods since it launched, which may be the reason why its churn rate is higher compared to its competitors.")
st.subheader(":blue[9. What is a good churn rate ?]")
st.write("A good or 'acceptable' churn rate is from 2% to 8%, especially for B2C SaaS businesses that offer self-serve solutions. The lower, the better, or it can significantly impact your Monthly Recurring Revenue (MRR). For B2B SaaS businesses with high average contract values (greater than $1,000 per month), churn rate should be below 2%.")
st.subheader(":blue[10. What is annual churn rate ?]")
st.write("Annual churn rate refers to the percentage of customers lost over the course of a year. To calculate annual churn rate, you would look at the number of customers you had at the beginning of the year, then look at the number you had at the end of the year.")
st.write("Subtract those two numbers. After, divide that by the amount of customers you had at the start of the year, and multiply by 100.")
st.write("For example, let's say you had 1,000 customers at the beginning of the year and 800 at the end of the year.")
st.write("(1,000 - 800) ÷ 1,000 x 100 = annual churn rate")
st.write("(200) ÷ 1,000 x 100 = 20")
st.write("The annual churn rate would be 20%.")
st.subheader(":blue[11. What is monthly churn rate ?]")
st.write("Monthly churn rate refers to the percentage of customers lost over the course of a month. To calculate monthly churn rate, divide the number of customers you lost over the month by the number of customers you had at the beginning of the month. Multiply the result by 100.")
st.write("Let's try an example with real numbers. We'll go with 200 customers lost with 1,200 customers at the beginning of the month.")
st.write("(200 ÷ 1,200) x 100 = monthly churn rate")
st.write("0.16 x 100 = 16")
st.write("The monthly churn rate is 16%.")
st.subheader(":blue[12. What is revenue churn rate ?]")
st.write("Revenue churn rate is a metric that measures the amount of revenue a business has lost due to customer churn during a given time period.")
st.write("It's critical to keep an eye on your revenue churn rate because it directly affects the financial health of your business. If your company is losing a significant portion of its revenue due to customer churn or service downgrades, it can negatively impact your financial stability and profitability in the long term.")
st.write("Revenue churn rate is also an important metric because it provides insight into the long-term value of your customers. If your revenue churn rate is too high, it could indicate that your customers are not finding enough value in your product or service, or that your retention efforts could be improved.")
st.subheader(":blue[13. How to Calculate Revenue Churn Rate ?]")
st.write("To calculate revenue churn rate, you need to know the revenue lost due to customer churn and the total revenue generated by your business during a specific time period. Divide the revenue lost due to customer churn by the total revenue generated. Then, multiply that number by 100 to get a percentage. Here's the formula:")
st.write("Revenue churn rate = (Revenue lost due to customer churn / Total revenue generated) x 100")
st.write("As an example, let's say your company generated 1 million in revenue in a month, and during that month lost $100,000 due to customer churn, the revenue churn rate would be calculated as follows:")
st.write("Revenue Churn Rate = (100,000 ÷ 1,000,000) x 100")
st.write("Revenue Churn Rate = (0.10) x 100")
st.write("Revenue Churn Rate = 10%")
st.subheader(":blue[14. Customer Churn Rate vs Revenue Churn Rate.]")
st.write("Customer churn rate measures the percentage of customers who have stopped using your product or service, while revenue churn rate measures the percentage of revenue that has been lost due to customer churn.")
st.write("Though customer churn rate and revenue churn rate are related, it's imperative to differentiate them because their results can mean very different things, especially for SaaS companies with multiple product tiers.")
st.write("For example, if you notice a high customer churn rate, but revenue churn rate remains low, it might indicate that customers are downsizing to a lower-tier product rather than leaving altogether. On the flip side, if the revenue churn rate is high, but the customer churn rate is low, it might mean that the business is losing its largest customers.")
st.write("By understanding both metrics, your business can take corrective action to improve customer retention rates and reduce churn, while protecting your revenue streams at the same time.")
st.subheader(":blue[15. How can I track churn ?]")
st.write("Tracking churn over time can be done in a number of ways. You can keep a spreadsheet with your findings and visualize it using the spreadsheet's built-in data visualization tool. You can also use a dedicated reporting dashboard software such as HubSpot's to automatically calculate and track churn.")
st.subheader(":blue[16. What is the difference between attrition and churn ?]")
st.write("Customer attrition is the same as customer churn. It's also referred to as customer turnover and customer defection.")
st.write("Although the terms vary, they are all referring to churn and can be used interchangeably.")
st.subheader(":blue[17. Calculate Churn Rate to Reduce Customer Turnover.]")
st.write("Calculating churn rate may seem like an unpleasant task, but it's critical to track it to understand what may be going wrong on a customer service level. Calculate customer churn rate over a year or a month, improve your customer service systems, invest in your customer service reps, and watch your churn rate decrease exponentially.")
